module.exports = {
  connection: "connection",
  login: "login",
  getOnlineUsers: "getOnlineUsers",
  disconnect: "disconnect",
  singleRoomChat: "singleRoomChat",
  receiveSingleChat: "receiveSingleChat",
  singleRoomsInfo: "singleRoomsInfo",
  joinRoom: "joinRoom",
  leaveRoom: "leaveRoom",
  sendFriendRequest: "sendFriendRequest",
  receiveFriendRequest: "receiveFriendRequest",
  acceptFriendRequest: "acceptFriendRequest",
  alertAcceptFriendRequest: "alertAcceptFriendRequest",
  sendChatInvite: "sendChatInvite",
  receiveChatInvite: "receiveChatInvite",
};
